name: CI
on:
  push:
    branches:
      - invento
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: frappe/frappe_docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Frappe Docker Image
        run: |
          export APPS_JSON='[
            {
            "url": "https://github.com/frappe/erpnext",
            "branch": "version-15"
            },
            {
            "url": "https://github.com/frappe/hrms.git",
            "branch": "version-15"
            },
            {
            "url": "https://github.com/sohan653/task_hrms.git",
            "branch": "invento"
            }
            
          ]
          '

          export APPS_JSON_BASE64=$(echo ${APPS_JSON} | base64 -w 0)

          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --build-arg FRAPPE_PATH=https://github.com/frappe/frappe \
          --build-arg FRAPPE_BRANCH=version-15 \
          --build-arg PYTHON_VERSION=3.11.9 \
          --build-arg NODE_VERSION=18.20.2 \
          --build-arg APPS_JSON_BASE64="$APPS_JSON_BASE64" \
          --tag sohanur653/task_hrms:dev-test \
          --file images/custom/Containerfile \
          --push .
